<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class ProgrammesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $programmes = [
            ['id' => 1, 'code' => 'C00097', 'department_id' => 1, 'name' => 'M.Sc. ACCOUNTING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 2, 'code' => 'C00098', 'department_id' => 1, 'name' => 'M.Sc. ACCOUNTING AND FINANCE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 3, 'code' => 'C00099', 'department_id' => 1, 'name' => 'PhD ACCOUNTING AND FINANCE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 4, 'code' => 'C00100', 'department_id' => 9, 'name' => 'M.Sc. BIOLOGY (CYTOGENETICS AND PLANT BREEDING)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 5, 'code' => 'C00101', 'department_id' => 9, 'name' => 'M.Sc. BOTANY AND ZOOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 6, 'code' => 'C00102', 'department_id' => 9, 'name' => 'M.Sc. ZOOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 7, 'code' => 'C00103', 'department_id' => 9, 'name' => 'M.Sc. APPLIED PARASITOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 8, 'code' => 'C00104', 'department_id' => 9, 'name' => 'M.Sc. HYDROBIOLOGY AND FISHERIES', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 9, 'code' => 'C00105', 'department_id' => 9, 'name' => 'M.Sc. PARASITOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 10, 'code' => 'C00106', 'department_id' => 9, 'name' => 'M.Sc. PURE AND APPLIED PARASITOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 11, 'code' => 'C00107', 'department_id' => 9, 'name' => 'PhD APPLIED ENTONOMOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 12, 'code' => 'C00108', 'department_id' => 9, 'name' => 'PhD PLANT PATHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 13, 'code' => 'C00109', 'department_id' => 9, 'name' => 'PhD PLANT PATHOLOGY AND BIOLOGICAL CONTROL OF PLANT DISEASE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 14, 'code' => 'C00110', 'department_id' => 12, 'name' => 'POSTGRADUATE DIPLOMA IN MANAGEMENT (PGDM)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 15, 'code' => 'C00111', 'department_id' => 16, 'name' => 'M.Sc. ANALYTICAL CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 16, 'code' => 'C00112', 'department_id' => 16, 'name' => 'M.Sc. CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 17, 'code' => 'C00113', 'department_id' => 16, 'name' => 'M.Sc. INORGANIC CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 18, 'code' => 'C00114', 'department_id' => 16, 'name' => 'M.Sc. ORGANIC CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 19, 'code' => 'C00115', 'department_id' => 16, 'name' => 'M.Sc. PHYSICAL CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 20, 'code' => 'C00116', 'department_id' => 6, 'name' => 'M.Ed. CURRICULUM AND INSTRUCTION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 21, 'code' => 'C00117', 'department_id' => 6, 'name' => 'M.Ed. LANGUAGE EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 22, 'code' => 'C00118', 'department_id' => 69, 'name' => 'M.Ed. MATHEMATICS EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 23, 'code' => 'C00119', 'department_id' => 69, 'name' => 'M.Ed. SCIENCE EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 24, 'code' => 'C00120', 'department_id' => 6, 'name' => 'M.Ed. SOCIAL STUDIES EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 25, 'code' => 'C00121', 'department_id' => 6, 'name' => 'PhD LANGUAGE EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 26, 'code' => 'C00122', 'department_id' => 69, 'name' => 'PhD MATHEMATICS EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 27, 'code' => 'C00123', 'department_id' => 69, 'name' => 'PhD SCIENCE EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 28, 'code' => 'C00124', 'department_id' => 6, 'name' => 'PhD SOCIAL STUDIES EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 29, 'code' => 'C00125', 'department_id' => 24, 'name' => 'M.Sc. ECONOMICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 30, 'code' => 'C00126', 'department_id' => 24, 'name' => 'PhD ECONOMICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 31, 'code' => 'C00127', 'department_id' => 25, 'name' => 'M.Ed. EDUCATIONAL MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 32, 'code' => 'C00128', 'department_id' => 25, 'name' => 'M.Ed. GUIDANCE AND COUNSELLING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 33, 'code' => 'C00129', 'department_id' => 25, 'name' => 'M.Sc. (Ed) SPORT MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 34, 'code' => 'C00130', 'department_id' => 25, 'name' => 'M.Sc. EXERCISE AND SPORTS SCIENCE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 35, 'code' => 'C00131', 'department_id' => 25, 'name' => 'PhD GUIDANCE AND COUNSELLING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 36, 'code' => 'C00132', 'department_id' => 25, 'name' => 'POSTGRADUATE DIPLOMA IN EDUCATION (PGDE)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 37, 'code' => 'C00133', 'department_id' => 26, 'name' => 'M.A. LITERATURE IN ENGLISH', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 38, 'code' => 'C00134', 'department_id' => 28, 'name' => 'M.Sc. DEVELOPMENT STUDIES', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 39, 'code' => 'C00135', 'department_id' => 28, 'name' => 'M.Sc. GEOGRAPHY ( HYDROLOGY AND WATER RESOURCES)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 40, 'code' => 'C00136', 'department_id' => 28, 'name' => 'M.Sc. GEOGRAPHY (CLIMATOLOGY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 41, 'code' => 'C00137', 'department_id' => 28, 'name' => 'M.Sc. GEOGRAPHY (ENVIRONMENTAL AND RESOURCE MANAGEMENT)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 42, 'code' => 'C00138', 'department_id' => 73, 'name' => 'MASTER OF URBAN AND REGIONAL PLANNING (MURP)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 43, 'code' => 'C00139', 'department_id' => 28, 'name' => 'PhD PLANNING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 44, 'code' => 'C00140', 'department_id' => 28, 'name' => 'PhD GEOGRAPHY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 45, 'code' => 'C00141', 'department_id' => 31, 'name' => 'M.A. HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 46, 'code' => 'C00142', 'department_id' => 31, 'name' => 'PhD HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 47, 'code' => 'C00143', 'department_id' => 36, 'name' => 'M.A. FRENCH', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 48, 'code' => 'C00144', 'department_id' => 36, 'name' => 'M.A. LANGUAGES AND LINGUISTICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 49, 'code' => 'C00145', 'department_id' => 36, 'name' => 'PhD FRANCOPHONE AFRICAN/CARIBBEAN LITERATURES', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 50, 'code' => 'C00146', 'department_id' => 36, 'name' => 'PhD FRENCH', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 51, 'code' => 'C00147', 'department_id' => 36, 'name' => 'PhD FRENCH LANGUAGE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 52, 'code' => 'C00148', 'department_id' => 36, 'name' => 'PhD METROPOLITANT FRENCH LITERATURE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 53, 'code' => 'C00149', 'department_id' => 37, 'name' => 'LL.M (LAW)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 54, 'code' => 'C00150', 'department_id' => 37, 'name' => 'PhD LAW', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 55, 'code' => 'C00151', 'department_id' => 41, 'name' => 'M.Sc. MASS COMMUNICATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 56, 'code' => 'C00152', 'department_id' => 41, 'name' => 'PhD MASS COMMUNICATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 57, 'code' => 'C00153', 'department_id' => 41, 'name' => 'POSTGRADUATE DIPLOMA IN MASS COMMUNICATION (PGDMC)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 58, 'code' => 'C00154', 'department_id' => 53, 'name' => 'M.Sc. PHYSICS (RADIATION AND MEDICAL PHYSICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 59, 'code' => 'C00155', 'department_id' => 53, 'name' => 'M.Sc. PHYSICS (THEORETICAL PHYSICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 60, 'code' => 'C00156', 'department_id' => 53, 'name' => 'PhD PHYSICS (RADIATION AND MEDICAL PHYSICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 61, 'code' => 'C00157', 'department_id' => 53, 'name' => 'PhD PHYSICS (THEORETICAL PHYSICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 62, 'code' => 'C00158', 'department_id' => 54, 'name' => 'M.Sc. INTERNATIONAL RELATIONS AND STRATEGIC STUDIES (IRSS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 63, 'code' => 'C00160', 'department_id' => 57, 'name' => 'M.Sc. PUBLIC ADMINISTRATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 64, 'code' => 'C00161', 'department_id' => 54, 'name' => 'MASTER OF ARTS INTERNATIONAL RELATIONS AND STRATEGIC STUDIES (IRSS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 65, 'code' => 'C00162', 'department_id' => 57, 'name' => 'MASTER OF PUBLIC ADMINISTRATION (MPA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 66, 'code' => 'C00163', 'department_id' => 54, 'name' => 'PhD POLITICAL SCIENCE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 67, 'code' => 'C00164', 'department_id' => 56, 'name' => 'M.Sc. CLINICAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 68, 'code' => 'C00165', 'department_id' => 56, 'name' => 'M.Sc. INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 69, 'code' => 'C00166', 'department_id' => 56, 'name' => 'MASTER IN HEALTH MANAGEMENT (MHM)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 70, 'code' => 'C00167', 'department_id' => 56, 'name' => 'PhD HEALTH MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 71, 'code' => 'C00168', 'department_id' => 56, 'name' => 'PhD PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 72, 'code' => 'C00169', 'department_id' => 56, 'name' => 'PhD CLINICAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 73, 'code' => 'C00170', 'department_id' => 61, 'name' => 'PhD RELIGIOUS STUDIES (AFRICAN TRADITIONAL RELIGION)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 74, 'code' => 'C00171', 'department_id' => 61, 'name' => 'PhD RELIGIOUS STUDIES (CHRISTIAN ETHICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 75, 'code' => 'C00172', 'department_id' => 61, 'name' => 'M.A. RELIGIOUS STUDIES (AFRICAN RELIGION)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 76, 'code' => 'C00173', 'department_id' => 70, 'name' => 'M.Sc. GENDER STUDIES', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 77, 'code' => 'C00174', 'department_id' => 70, 'name' => 'M.Sc. SOCIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 78, 'code' => 'C00175', 'department_id' => 70, 'name' => 'PhD SOCIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 79, 'code' => 'C00176', 'department_id' => 72, 'name' => 'M.A. THEATRE ARTS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 80, 'code' => 'C00177', 'department_id' => 72, 'name' => 'PhD THEATRE ARTS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 81, 'code' => 'C00178', 'department_id' => 25, 'name' => 'M.Sc. (ED) HEALTH EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 82, 'code' => 'C00179', 'department_id' => 56, 'name' => 'PhD INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 83, 'code' => 'C00180', 'department_id' => 26, 'name' => 'PhD LITERATURE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 84, 'code' => 'C00181', 'department_id' => 6, 'name' => 'PhD CURRICULUM AND INSTRUCTION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 85, 'code' => 'C00182', 'department_id' => 9, 'name' => 'PhD PURE AND APPLIED PARASITOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 86, 'code' => 'C00183', 'department_id' => 28, 'name' => 'M.Sc. GEOGRAPHY (GEOMORPHOLOGY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 87, 'code' => 'C00205', 'department_id' => 34, 'name' => 'M.Sc. TECHNOLOGY EDUCATION (MECH)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 88, 'code' => 'C00206', 'department_id' => 34, 'name' => 'M.Sc. TECHNOLOGY EDUCATION (ELECT/ELECTRO)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 89, 'code' => 'C00207', 'department_id' => 34, 'name' => 'M.Sc. TECHNOLOGY EDUCATION (CONST)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 90, 'code' => 'C00208', 'department_id' => 9, 'name' => 'M.Sc. PLANT PATHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 91, 'code' => 'C00209', 'department_id' => 61, 'name' => 'PhD RELIGIOUS STUDIES (OLD TESTAMENT)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 92, 'code' => 'C00210', 'department_id' => 61, 'name' => 'PhD RELIGIOUS STUDIES (NEW TESTAMENT)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 93, 'code' => 'C00211', 'department_id' => 54, 'name' => 'M.Sc. POLITICAL SCIENCE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 94, 'code' => 'C00212', 'department_id' => 36, 'name' => 'PhD LINGUISTICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 95, 'code' => 'C00213', 'department_id' => 12, 'name' => 'PhD MARKETING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 96, 'code' => 'C00214', 'department_id' => 12, 'name' => 'PhD MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 97, 'code' => 'C00215', 'department_id' => 9, 'name' => 'PhD HYDROBIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 98, 'code' => 'C00216', 'department_id' => 12, 'name' => 'MASTERS IN BUSINESS MANAGEMENT (MBA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 99, 'code' => 'C00217', 'department_id' => 26, 'name' => 'PhD ENGLISH', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 100, 'code' => 'C00218', 'department_id' => 28, 'name' => 'PhD GEOGRAPHY (RURAL DEVELOPMENT)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 101, 'code' => 'C00221', 'department_id' => 25, 'name' => 'M.Sc. HEALTH MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 102, 'code' => 'C10182', 'department_id' => 61, 'name' => 'PhD CHURCH HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 103, 'code' => 'C10750', 'department_id' => 28, 'name' => 'M.Sc. GEOGRAPHY (URBAN GEOGRAPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 104, 'code' => 'C11207', 'department_id' => 25, 'name' => 'PhD MARITAL AND FAMILY COUNSELLING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 105, 'code' => 'C11547', 'department_id' => 31, 'name' => 'M.A. ECONOMIC HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 106, 'code' => 'C11738', 'department_id' => 4, 'name' => 'M.Sc. HUMAN ANATOMY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 107, 'code' => 'C12401', 'department_id' => 41, 'name' => 'M.Sc. MASS COMMUNICATION(PUBLIC RELATIONS AND ADVERTISING)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 108, 'code' => 'C12575', 'department_id' => 54, 'name' => 'PhD POLITICAL SCIENCE(INTERNATIONAL RELATIONS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 109, 'code' => 'C12916', 'department_id' => 12, 'name' => 'M.Sc/PhD MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 110, 'code' => 'C13667', 'department_id' => 25, 'name' => 'PhD SCHOOL COUNSELLING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 111, 'code' => 'C13956', 'department_id' => 2, 'name' => 'PhD PHILOSOPHY IN (AFRICAN PHILOSOPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 112, 'code' => 'C14170', 'department_id' => 28, 'name' => 'PhD GEOGRAPHY (POPULATION STUDIES)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 113, 'code' => 'C14569', 'department_id' => 12, 'name' => 'M.Sc. MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 114, 'code' => 'C14763', 'department_id' => 5, 'name' => 'M.Sc. HUMAN PHYSIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 115, 'code' => 'C15669', 'department_id' => 61, 'name' => 'M.A. RELIGIOUS STUDIES (OLD TESTAMENT)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 116, 'code' => 'C15858', 'department_id' => 56, 'name' => 'PhD HEALTH PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 117, 'code' => 'C16981', 'department_id' => 41, 'name' => 'M.Sc. MASS COMMUNICATION(ELECTRONIC MEDIA(RADIO, TELEVISION AND FILM))', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 118, 'code' => 'C20808', 'department_id' => 61, 'name' => 'M.A. RELIGIOUS STUDIES (SOCIOLOGY OF RELIGION)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 119, 'code' => 'C21098', 'department_id' => 70, 'name' => 'MASTERS IN GENDER, ECONOMIC EMPOWERMENT AND ENTREPRENEURSHIP', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 120, 'code' => 'C21710', 'department_id' => 16, 'name' => 'M.Sc POLYMER CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 121, 'code' => 'C21942', 'department_id' => 9, 'name' => 'PhD SYSTEMATIC AND TAXONOMY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 122, 'code' => 'C22285', 'department_id' => 54, 'name' => 'M.Sc. PEACE AND CONFLICT STUDIES', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 123, 'code' => 'C23106', 'department_id' => 2, 'name' => 'PhD PHILOSOPHY (ETHICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 124, 'code' => 'C23133', 'department_id' => 69, 'name' => 'M.Sc. (ED) MATHEMATICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 125, 'code' => 'C23476', 'department_id' => 53, 'name' => 'PhD ELECTRONICS AND COMMUNICATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 126, 'code' => 'C24393', 'department_id' => 9, 'name' => 'M.Sc. PLANT/TAXONOMY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 127, 'code' => 'C24908', 'department_id' => 61, 'name' => 'PhD RELIGIOUS STUDIES (COMPARATIVE RELIGIONS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 128, 'code' => 'C25239', 'department_id' => 54, 'name' => 'PhD POLITICAL SCIENCE(POLITICAL PHILOSOPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 129, 'code' => 'C25938', 'department_id' => 25, 'name' => 'PhD PERSONAL-SOCIAL COUNSELLING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 130, 'code' => 'C27848', 'department_id' => 61, 'name' => 'M.A. RELIGIOUS STUDIES (NEW TESTAMENT)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 131, 'code' => 'C30288', 'department_id' => 16, 'name' => 'M.Sc ENVIRONMENTAL TOXICOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 132, 'code' => 'C31018', 'department_id' => 2, 'name' => 'M.A. PHILOSOPHY (EPISTEMOLOGY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 133, 'code' => 'C31151', 'department_id' => 70, 'name' => 'MASTER IN LIBRARY AND INFORMATION SCIENCE (MLIS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 134, 'code' => 'C31383', 'department_id' => 28, 'name' => 'PhD GEOGRAPHY (CLIMATOLOGY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 135, 'code' => 'C32544', 'department_id' => 69, 'name' => 'M.Sc. (ED) PHYSICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 136, 'code' => 'C32816', 'department_id' => 70, 'name' => 'MASTERS IN GENDER, MEDIA, LANGUAGE AND ARTS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 137, 'code' => 'C33679', 'department_id' => 5, 'name' => 'PhD HUMAN PHYSIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 138, 'code' => 'C34515', 'department_id' => 54, 'name' => 'PhD POLITICAL SCIENCE(POLITICAL ECONOMY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 139, 'code' => 'C34943', 'department_id' => 16, 'name' => 'M.Sc INDUSTRIAL CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 140, 'code' => 'C35015', 'department_id' => 54, 'name' => 'M.Sc. PEACE STUDIES AND CONFLICT RESOLUTION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 141, 'code' => 'C35125', 'department_id' => 61, 'name' => 'M.A. RELIGIOUS STUDIES (COMPARATIVE RELIGIONS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 142, 'code' => 'C35128', 'department_id' => 69, 'name' => 'M. Ed. MEASUREMENT AND EVALUATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 143, 'code' => 'C36600', 'department_id' => 69, 'name' => 'M.Sc. (ED) CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 144, 'code' => 'C37128', 'department_id' => 61, 'name' => 'M.A. CHURCH HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 145, 'code' => 'C37454', 'department_id' => 56, 'name' => 'PhD EXPERIMENTAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 146, 'code' => 'C38026', 'department_id' => 28, 'name' => 'M.Sc. ENVIRONMENTAL MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 147, 'code' => 'C38090', 'department_id' => 53, 'name' => 'M.Sc MEDICAL PHYSICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 148, 'code' => 'C39214', 'department_id' => 73, 'name' => 'M.Sc. ENVIRONMENTAL PLANNING AND MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 149, 'code' => 'C39223', 'department_id' => 25, 'name' => 'PhD (Ed) Physical and Health Education', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 150, 'code' => 'C39522', 'department_id' => 16, 'name' => 'PhD CHEMISTRY (ANALYTICAL/ENVIRONMENTAL CHEMISTRY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 151, 'code' => 'C39972', 'department_id' => 9, 'name' => 'PhD ZOOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 152, 'code' => 'C42258', 'department_id' => 25, 'name' => 'M.Ed. EDUCATIONAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 153, 'code' => 'C42514', 'department_id' => 2, 'name' => 'M.A. PHILOSOPHY (ETHICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 154, 'code' => 'C42654', 'department_id' => 1, 'name' => 'PhD ACCOUNTING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 155, 'code' => 'C43109', 'department_id' => 31, 'name' => 'M.A. HISTORIOGRAPHY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 156, 'code' => 'C44196', 'department_id' => 16, 'name' => 'PhD POLYMER CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 157, 'code' => 'C44638', 'department_id' => 73, 'name' => 'M.Sc. SOCIAL SERVICES PLANNING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 158, 'code' => 'C44870', 'department_id' => 5, 'name' => 'MASTERS OF REPRODUCTIVE HEALTH (MRH)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 159, 'code' => 'C45788', 'department_id' => 25, 'name' => 'PhD EDUCATIONAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 160, 'code' => 'C46333', 'department_id' => 70, 'name' => 'MASTERS IN GENDER, EDUCATION AND PROFESSIONS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 161, 'code' => 'C46841', 'department_id' => 41, 'name' => 'PhD MASS COMMUNICATION(PRINT MEDIA SEQUENCE)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 162, 'code' => 'C47056', 'department_id' => 54, 'name' => 'PhD POLITICAL SCIENCE(EMPIRICAL POLITICAL THEORY AND METHODOLOGY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 163, 'code' => 'C47380', 'department_id' => 9, 'name' => 'PhD CYTOGENETICS AND PLANT BREEDING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 164, 'code' => 'C47442', 'department_id' => 53, 'name' => 'M.Sc RADIATION PHYSICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 165, 'code' => 'C47982', 'department_id' => 70, 'name' => 'M.Sc. RURAL SOCIOLOGY & AGRICULTURAL EXTENSION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 166, 'code' => 'C49853', 'department_id' => 34, 'name' => 'PhD INDUSTRIAL TECHNOLOGY EDUCATION (MECHANICAL/PRODUCTION/AUTOMOBILE)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 167, 'code' => 'C50813', 'department_id' => 70, 'name' => 'MASTERS IN GENDER, ENVIRONMENT AND CLIMATE CHANGE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 168, 'code' => 'C51693', 'department_id' => 28, 'name' => 'M.Sc. GEOGRAPHY (POPULATION STUDIES)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 169, 'code' => 'C51978', 'department_id' => 41, 'name' => 'PhD MASS COMMUNICATION(ELECTRONIC MEDIA SEQUENC)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 170, 'code' => 'C52565', 'department_id' => 26, 'name' => 'M.A. ENGLISH', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 171, 'code' => 'C54194', 'department_id' => 54, 'name' => 'PhD POLITICAL SCIENCE(COMPARATIVE POLITICS AND DEVELOPMENT STUDIES)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 172, 'code' => 'C54479', 'department_id' => 34, 'name' => 'PhD INDUSTRIAL TECHNOLOGY EDUCATION (CONSTRUCTION)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 173, 'code' => 'C54545', 'department_id' => 70, 'name' => 'PhD RURAL SOCIOLOGY & AGRICULTURAL EXTENSION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 174, 'code' => 'C54584', 'department_id' => 56, 'name' => 'PhD DEVELOPMENTAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 175, 'code' => 'C54898', 'department_id' => 16, 'name' => 'PhD ENVIRONMENTAL CONTROL & SUSTAINABILITY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 176, 'code' => 'C55712', 'department_id' => 54, 'name' => 'PhD POLITICAL SCIENCE(DIPLOMACY AND STRATEGIC STUDIES)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 177, 'code' => 'C56968', 'department_id' => 1, 'name' => 'MASTERS IN PUBLIC SECTOR ACCOUNTING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 178, 'code' => 'C57041', 'department_id' => 34, 'name' => 'PhD INDUSTRIAL TECHNOLOGY EDUCATION (ELECTRICAL/ELECTRONICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 179, 'code' => 'C57246', 'department_id' => 2, 'name' => 'PhD PHILOSOPHY (METAPHYSICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 180, 'code' => 'C58013', 'department_id' => 70, 'name' => 'MASTERS IN GENDER, SECURITY, CONFLICT AND PEACE BUILDING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 181, 'code' => 'C59047', 'department_id' => 28, 'name' => 'M.Sc. GEOGRAPHY (RURAL GEOGRAPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 182, 'code' => 'C60096', 'department_id' => 25, 'name' => 'PhD PUBLIC HEALTH EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 183, 'code' => 'C60250', 'department_id' => 16, 'name' => 'PhD ENVIRONMENTAL TOXICOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 184, 'code' => 'C60706', 'department_id' => 2, 'name' => 'PhD PHILOSOPHY IN (EPISTEMOLOGY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 185, 'code' => 'C60889', 'department_id' => 69, 'name' => 'PhD MEASUREMENT AND EVALUATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 186, 'code' => 'C61045', 'department_id' => 31, 'name' => 'PhD NIGERIAN HISTORY (WITH PARTICULAR EMPHASIS ON CENTRAL NIGERIA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 187, 'code' => 'C61046', 'department_id' => 31, 'name' => 'PhD AFRICAN HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 188, 'code' => 'C61047', 'department_id' => 31, 'name' => 'PhD ECONOMIC HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 189, 'code' => 'C61048', 'department_id' => 31, 'name' => 'PhD HISTORIOGRAPHY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 190, 'code' => 'C61049', 'department_id' => 31, 'name' => 'PhD DIPLOMATIC HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 191, 'code' => 'C61050', 'department_id' => 31, 'name' => 'PhD CULTURAL HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 192, 'code' => 'C61053', 'department_id' => 72, 'name' => 'M.A. COMMUNITY THEARTRE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 193, 'code' => 'C61054', 'department_id' => 72, 'name' => 'M.A. THEATRE ADMINISTRATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 194, 'code' => 'C61055', 'department_id' => 72, 'name' => 'M.A. DRAMATIC LITERTATURE AND CRITICISM', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 195, 'code' => 'C61056', 'department_id' => 72, 'name' => 'M.A. DIRECTING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 196, 'code' => 'C61057', 'department_id' => 72, 'name' => 'M.A. MEDIA ARTS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 197, 'code' => 'C61058', 'department_id' => 72, 'name' => 'M.A. DRAMA IN EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 198, 'code' => 'C61059', 'department_id' => 72, 'name' => 'M.A. ACTING AND CHOREOGRAPHY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 199, 'code' => 'C61069', 'department_id' => 24, 'name' => 'PhD DEVELOPMENT ECONOMICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 200, 'code' => 'C61070', 'department_id' => 24, 'name' => 'PhD MONETRARY ECONOMICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 201, 'code' => 'C61071', 'department_id' => 24, 'name' => 'PhD PUBLIC FINANCE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 202, 'code' => 'C61073', 'department_id' => 70, 'name' => 'M.Sc. CRIMINOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 203, 'code' => 'C61074', 'department_id' => 70, 'name' => 'M.Sc. DEMOGRAPHY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 204, 'code' => 'C61075', 'department_id' => 70, 'name' => 'M.Sc. DEVELOPMENT SOCIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 205, 'code' => 'C61076', 'department_id' => 70, 'name' => 'M.Sc. INDUSTRIAL SOCIOLOGY AND LABOUR RELATIONS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 206, 'code' => 'C61077', 'department_id' => 70, 'name' => 'M.Sc. MEDICAL SOCIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 207, 'code' => 'C61078', 'department_id' => 70, 'name' => 'M.Sc. RURAL SOCIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 208, 'code' => 'C61082', 'department_id' => 28, 'name' => 'M.Sc. URBAN GEOGRAPHY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 209, 'code' => 'C61083', 'department_id' => 28, 'name' => 'M.Sc. HYDROLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 210, 'code' => 'C61085', 'department_id' => 73, 'name' => 'PhD URBAN AND REGIONAL PLANNING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 211, 'code' => 'C61087', 'department_id' => 9, 'name' => 'M.Sc. PURE AND APPLIED ENTOMOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 212, 'code' => 'C61089', 'department_id' => 9, 'name' => 'M.Sc. SYSTEMATIC AND TAXONOMY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 213, 'code' => 'C61090', 'department_id' => 9, 'name' => 'PhD PURE AND APPLIED ENTOMOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 214, 'code' => 'C61091', 'department_id' => 9, 'name' => 'PhD HYDROBIOLOGY AND FISHERIES', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 215, 'code' => 'C61093', 'department_id' => 53, 'name' => 'M.Sc. ATMOSPHERIC AND ENVIRONMENTAL PHYSICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 216, 'code' => 'C61278', 'department_id' => 56, 'name' => 'PhD SOCIAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 217, 'code' => 'C62242', 'department_id' => 28, 'name' => 'M.Sc. ENVIRONMENTAL MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 218, 'code' => 'C62520', 'department_id' => 70, 'name' => 'POSTGRADUATE DIPLOMA IN GENDER STUDIES', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 219, 'code' => 'C64859', 'department_id' => 16, 'name' => 'PhD CHEMISTRY (INORGANIC CHEMISTRY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 220, 'code' => 'C65428', 'department_id' => 2, 'name' => 'M.A. PHILOSOPHY (AFRICAN PHILOSOPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 221, 'code' => 'C66309', 'department_id' => 73, 'name' => 'POSTGRADUATE DIPLOMA IN PLANNING STUDIES (PDPS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 222, 'code' => 'C66464', 'department_id' => 16, 'name' => 'M.Sc POLLUTION AND CONTROL', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 223, 'code' => 'C66870', 'department_id' => 53, 'name' => 'POSTGRADUATE DIPLOMA IN COMPUTER SCIENCE (PGDCS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 224, 'code' => 'C67114', 'department_id' => 70, 'name' => 'MASTERS IN GENDER AND HEALTH', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 225, 'code' => 'C67991', 'department_id' => 56, 'name' => 'M.Sc. SOCIAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 226, 'code' => 'C68091', 'department_id' => 12, 'name' => 'MASTERS IN MARKETING (MBA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 227, 'code' => 'C68568', 'department_id' => 53, 'name' => 'M.Sc. COMPUTER SCIENCE', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 228, 'code' => 'C68837', 'department_id' => 16, 'name' => 'PhD CHEMISTRY (PHYSICAL CHEMISTRY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 229, 'code' => 'C69362', 'department_id' => 34, 'name' => 'PhD INDUSTRIAL TECHNOLOGY EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 230, 'code' => 'C69784', 'department_id' => 25, 'name' => 'PhD EDUCATIONAL MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 231, 'code' => 'C70147', 'department_id' => 70, 'name' => 'MASTERS IN GENDER, HUMAN RIGHTS, GOVERNANCE AND DEMOCRACY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 232, 'code' => 'C73178', 'department_id' => 25, 'name' => 'PhD (Ed) Exercise and Sport Science', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 233, 'code' => 'C73644', 'department_id' => 28, 'name' => 'PhD. GEOGRAPHY (ENVIRONMENTAL AND RESOURCE MANAGEMENT)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 234, 'code' => 'C73799', 'department_id' => 70, 'name' => 'MASTERS IN GENDER STUDIES (MGS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 235, 'code' => 'C74296', 'department_id' => 12, 'name' => 'MASTERS IN ACCOUNTING AND FINANCE (MBA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 236, 'code' => 'C74469', 'department_id' => 1, 'name' => 'MASTERS IN BANKING AND FINANCE (MBA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 237, 'code' => 'C74836', 'department_id' => 69, 'name' => 'M.Sc. Ed SCIENCE EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 238, 'code' => 'C74891', 'department_id' => 16, 'name' => 'PhD INDUSTRIAL CHEMISTRY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 239, 'code' => 'C75393', 'department_id' => 31, 'name' => 'M.A. AFRICAN HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 240, 'code' => 'C75909', 'department_id' => 25, 'name' => 'M.Sc. (Ed) PHYSICAL AND HEALTH EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 241, 'code' => 'C76378', 'department_id' => 61, 'name' => 'M.A. RELIGIOUS STUDIES (CHRISTIAN ETHICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 242, 'code' => 'C77079', 'department_id' => 16, 'name' => 'PhD CHEMISTRY (ORGANIC /NATURAL PRODUCTS CHEMISTRY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 243, 'code' => 'C78271', 'department_id' => 25, 'name' => 'M.Sc. HUMAN KINETICS AND HEALTH EDUCATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 244, 'code' => 'C80674', 'department_id' => 73, 'name' => 'M.Sc. URBAN DESIGN', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 245, 'code' => 'C82016', 'department_id' => 73, 'name' => 'M.Sc. REGIONAL PLANNING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 246, 'code' => 'C82667', 'department_id' => 69, 'name' => 'M.Sc. (ED) BIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 247, 'code' => 'C83633', 'department_id' => 2, 'name' => 'PhD PHILOSOPHY (SOCIAL AND POLITICAL PHILOSOPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 248, 'code' => 'C83940', 'department_id' => 53, 'name' => 'M.Sc. MATHEMATICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 249, 'code' => 'C84790', 'department_id' => 53, 'name' => 'PhD MEDICAL PHYSICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 250, 'code' => 'C85526', 'department_id' => 73, 'name' => 'M.Sc. HOUSING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 251, 'code' => 'C85948', 'department_id' => 25, 'name' => 'PhD EDUCATIONAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 252, 'code' => 'C85956', 'department_id' => 1, 'name' => 'POST GRADUATE DIPLOMA IN ACCOUNTING(PGDA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 253, 'code' => 'C87488', 'department_id' => 41, 'name' => 'PhD MASS COMMUNICATION(PUBLIC RELATIONS AND ADVERTISING SEQUENCE)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 254, 'code' => 'C88552', 'department_id' => 53, 'name' => 'PhD RADIATION PHYSICS', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 255, 'code' => 'C89415', 'department_id' => 2, 'name' => 'M.A. PHILOSOPHY (SOCIAL AND POLITICAL PHILOSOPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 256, 'code' => 'C89597', 'department_id' => 70, 'name' => 'MASTERS IN GENDER, AGRICULTURE AND COMMUNITY DEVELOPMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 257, 'code' => 'C89961', 'department_id' => 56, 'name' => 'M.Sc. DEVELOPMENTAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 258, 'code' => 'C91513', 'department_id' => 73, 'name' => 'M.Sc. TRANSPORTATION PLANNING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 259, 'code' => 'C92069', 'department_id' => 9, 'name' => 'PhD BIOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 260, 'code' => 'C92533', 'department_id' => 25, 'name' => 'PhD (Ed) Sports Management', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 261, 'code' => 'C92680', 'department_id' => 61, 'name' => 'PhD RELIGIOUS STUDIES (SOCIOLOGY OF RELIGION)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 262, 'code' => 'C93113', 'department_id' => 28, 'name' => 'PhD. GEOGRAPHY (URBAN GEOGRAPHY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 263, 'code' => 'C93757', 'department_id' => 12, 'name' => 'M.Sc/PhD MARKETING', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 264, 'code' => 'C94749', 'department_id' => 2, 'name' => 'M.A. PHILOSOPHY (METAPHYSICS)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 265, 'code' => 'C95038', 'department_id' => 31, 'name' => 'M.A. NIGERIAN HISTORY(CENTRAL NIGERIA)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 266, 'code' => 'C95111', 'department_id' => 73, 'name' => 'M.Sc. URBAN MANAGEMENT', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 267, 'code' => 'C95309', 'department_id' => 53, 'name' => 'M.Sc. ELECTRONICS AND COMMUNICATION', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 268, 'code' => 'C95450', 'department_id' => 41, 'name' => 'M.Sc. MASS COMMUNICATION(PRINT MEDIA(NEWSPAPER AND MAGAZINE))', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 269, 'code' => 'C95696', 'department_id' => 4, 'name' => 'MASTER OF PUBLIC HEALTH (MPH)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 270, 'code' => 'C96483', 'department_id' => 16, 'name' => 'M.Sc. ENVIRONMENTAL CONTROL & SUSTAINABILITY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 271, 'code' => 'C96538', 'department_id' => 56, 'name' => 'POSTGRADUATE DIPLOMA IN PSYCHOLOGY (PGDPSY)', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 272, 'code' => 'C96551', 'department_id' => 56, 'name' => 'M.Sc. EXPERIMENTAL PSYCHOLOGY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 273, 'code' => 'C97136', 'department_id' => 4, 'name' => 'PhD HUMAN ANATOMY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 274, 'code' => 'C97301', 'department_id' => 31, 'name' => 'M.A. DIPLOMATIC HISTORY', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 275, 'code' => 'C97787', 'department_id' => 53, 'name' => 'PhD Atmospheric and Environmental Physics', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
            ['id' => 276, 'code' => 'C99254', 'department_id' => 16, 'name' => 'PhD POLLUTION AND CONTROL', 'min_score' => 40, 'archive' => 0, 'category' => 'POST GRADUATE'],
        ];

        foreach ($programmes as $programme) {
            DB::table('programmes')->insert([
                'id' => $programme['id'],
                'code' => $programme['code'],
                'department_id' => $programme['department_id'],
                'name' => $programme['name'],
                'min_score' => $programme['min_score'],
                'archive' => $programme['archive'],
                'category' => $programme['category'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }   
    }
    
}
