name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET }}/
          exclude: |
            **/.git*
            **/.github*
            node_modules/
            storage/
            .env

      # Optionally upload .env and deploy.sh
      - name: Upload .env and deploy.sh (optional)
        run: |
          if [ -n "${{ secrets.ENV_FILE }}" ]; then
            echo "${{ secrets.ENV_FILE }}" > .env
            curl -T .env -u "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" "ftp://${{ secrets.FTP_SERVER }}/${{ secrets.FTP_TARGET }}/.env"
          fi
          curl -T deploy.sh -u "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" "ftp://${{ secrets.FTP_SERVER }}/${{ secrets.FTP_TARGET }}/deploy.sh"